Kong/atc-router

- lib/resty/router/context.lua
- lib/resty/router/router.lua
- lib/resty/router/schema.lua
to avoid seg faults during GC
Verified with the following example, the bug is no longer present.
```
local schema = require("resty.router.schema")
local router = require("resty.router.router")
local s = schema.new()
local r = router.new(s)
schema = nil
router = nil
rawset(package.loaded, "resty.router.schema", nil)
rawset(package.loaded, "resty.router.router", nil)
rawset(package.loaded, "resty.router.cdefs", nil)
collectgarbage()
s = nil
r = nil
collectgarbage()
print("ok")
```
> fix(*) ensure `clib` outlives object instances created by this library

- Makefile
`which` is causing issues when building on some OS because that command is not found. (e.g. amazonlinux). we are getting the same check result with `ifeq (, $(shell cargo))`
> fix(*) do not use  to check if the cargo binary is installed

- lib/resty/router/cdefs.lua
On my M1 mac the `load_shared_lib` function does not work.
I have a weird thing happening with ATC router .so loading on my mac,  basically this code in `resty/router/cdefs.lua` causes an issue:
```
local fpath = string_match(k, "(.*/)")
fpath = fpath .. so_name
```
it errors with:
```
resty/router/cdefs.lua:112: attempt to concatenate local 'fpath' (a nil value)
```
If I print the `fpath` it gives me `string` value back, if I `print(type(fpath))` it prints `string` but in concatenation it still acts as a `nil`. Thus I was thinking that could there be strange things happening with `metatables`. The `metatable` for `fpath` is:
```
{
__index = {
byte = <function 1>,
char = <function 2>,
dump = <function 3>,
find = <function 4>,
format = <function 5>,
gmatch = <function 6>,
gsub = <function …
```
> fix(cdefs) atc router lib loading triggers some weird luajit bug

- lib/resty/router/cdefs.lua
- lib/resty/router/context.lua
- lib/resty/router/router.lua
- lib/resty/router/schema.lua
- t/02-gc.t
I moved anonymous free functions into `cdefs`,
I think it will make the code more clean and readable.
Does it make sense?
> chore(*)move free wrapper into cdefs

- Makefile
This check has proven to be somewhat error-prone, and it's a little bit handhold-y for a Makefile. If cargo is truly not installed, this error seems plenty explanatory for an average developer:
```
$ make build
cargo build --release
make: cargo: No such file or directory
make: *** [Makefile:27: target/release/libatc_router.so] Error 127
```
> chore(build): remove cargo binary check from Makefile

- .github/workflows/bazel.yml
- .github/workflows/lint.yml
- .github/workflows/tests.yml
This reduces GHA spend for this repo by:
- Cancelling in-flight builds for PRs when a newer commit is pushed
- Disables builds for `push` events for feature branches (`pull_request` and `push` for feature branches produces duplicate builds).
> chore(ci): reduce GHA spend

- src/atc_grammar.pest
- src/parser.rs
- t/04-rawstr.t
Now we can use \` to construct string so that we don't need to repeatedly write escape slashes.
_Fix KAG-370_
> feat(grammar) rawstring

- .github/workflows/lint.yml
- .github/workflows/sast.yml
- .github/workflows/sca.yml
Can I get a review on the shared action integration for Luacheck/ rust-clippy and rust sca using grype ?
- When the PR is merged, linters (lua / rust) runs on other `PR` and `main` branches and create checks and status reports based on changed and dirty files between commits
- Semgrep and rust CVE analysis is reported to GitHub code scanning for public repositories.
- https://github.com/Kong/public-shared-actions/tree/main/code-check-actions/rust-lint
- https://github.com/Kong/public-shared-actions/tree/main/code-check-actions/lua-lint
- https://github.com/Kong/public-shared-actions/tree/main/security-actions/semgrep
- https://github.com/Kong/public-shared-actions/tree/main/security-actions/scan-rust
> feat(ci): add lint and sca workflows using shared actions

- src/ast.rs
- src/atc_grammar.pest
- src/interpreter.rs
- src/parser.rs
- src/semantics.rs
- t/07-in_notin.t
- t/08-equals.t
IpCidr` matchings
https://konghq.atlassian.net/browse/KAG-1846
> fix(semantics): fix incorrect type checking that prevented `IpAddr in

- Makefile
Hi,
This PR is intended to include CARGO_BUILD_TARGET in the path of the release folder if it is specified.
If there are any problems, please let me know.
Thanks.
> build: include `CARGO_BUILD_TARGET` in the path of release folder

- Cargo.lock
- Cargo.toml
- src/ast.rs
- src/lib.rs
This pull request is a prerequisite for the external crate containing ATC Router's WASM binding
- Adding `lib` to `crate-type` to allow this crate to be used by other crates
- Adding a `serde` feature to apply `serde` macros selectively
- Adding a `no-ffi` feature to exclude `ffi` from mods to avoid symbol conflicts while being used as a dependency
KAG-2426
> feat(serde): add serde integration

- .github/workflows/bazel.yml
- BUILD.bazel
Added a test to ensure FFI module is being built. Resolves error like: https://github.com/Kong/kong/actions/runs/6718688600/job/18259139028.
> chore(build): ensure `ffi` feature is enabled when producing builds with Bazel

- Cargo.lock
- Cargo.toml
- README.md
- lib/resty/router/cdefs.lua
- lib/resty/router/context.lua
- src/ast.rs
- src/context.rs
- src/ffi.rs
- src/interpreter.rs
- src/parser.rs
Rust regex crate can not use faster lazy DFA based matching when we ask
for captures. As a router, the chance of regex mismatch is higher,
therefore, it makes sense to use `is_match()` to check if regex match
first with the faster implementation before asking for capture using the
slower implementations (onepass DFA, Pike VM (NFA)).
HashMap by default uses SipHash which is DDoS resilient, in case hash
key collision is not a risk (e.g. field names), it makes sense to use a
HashDos non-resilient hashing function (e.g. Fowler–Noll–Vo hash) which
runs two orders of magnitude faster.
These improvements showed up to 50% performance improvement in regex
heavy synthetic scenarios, or about 20% improvement in field access heavy
synthetic scenarios. …
> perf(interpreter): improve performance of regex matching and field reference

- src/context.rs
- t/01-sanity.t
`self.result` should also be cleared on match. This makes sure the context does not think it has a match result.
> fix(context): clear matches on reset

- src/ast.rs
- src/atc_grammar.pest
- src/interpreter.rs
- src/parser.rs
- src/semantics.rs
- t/09-not.t
The not operator `!` can be used with parenthesized expressions and will negate the result of the expressions.
Pratt parser is not used for this prefix operator because that would make:
```
! a == 1
```
Possible, which may cause confusions. Instead, this was implemented on the parenthesized expressions rule only so you can only write `! (a == 1)`.
[KAG-3605]
[KAG-3605]: https://konghq.atlassian.net/browse/KAG-3605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(lib): add "not" logical operator support

- Cargo.lock
```
Updating autocfg v1.3.0 -> v1.4.0
Updating cidr v0.2.2 -> v0.2.3 (latest: v0.3.0)
Updating clap v4.5.16 -> v4.5.20
Updating clap_builder v4.5.15 -> v4.5.20
Updating cpufeatures v0.2.12 -> v0.2.14
Updating js-sys v0.3.70 -> v0.3.72
Updating libc v0.2.153 -> v0.2.159
Updating memchr v2.7.2 -> v2.7.4
Updating once_cell v1.19.0 -> v1.20.2
Updating pest v2.7.11 -> v2.7.14
Updating pest_derive v2.7.11 -> v2.7.14
Updating pest_generator v2.7.11 -> v2.7.14
Updating pest_meta v2.7.11 -> v2.7.14
Updating plotters v0.3.6 -> v0.3.7
Updating plotters-backend v0.3.6 -> v0.3.7
Updating plotters-svg v0.3.6 -> v0.3.7
Updating proc-macro2 v1.0.80 -> v1.0.87
Updating quote v1.0.36 -> v1.0.37
Updating regex v1.10.5 -> v1.11.0
Updating regex-automata v0.4.6 -> v0.4.8
Updating regex-syntax v0.8.3 -> v0.8.5 …
```
> chore(deps): bump dependencies

- Cargo.toml
```
error: failed to publish to registry at https://crates.io
Caused by:
the remote server responded with an error (status 400 Bad Request): The following category slugs are not currently supported on crates.io: Compilers, Parser implementations
See https://crates.io/category_slugs for a list of supported slugs.
```
> chore(cargo): remove unsupported slug

- src/ffi/expression.rs
- src/ffi/router.rs
- src/interpreter.rs
- src/parser.rs
Manually removed the two empty lines but doesn't seem to have affected code generation. But generation doesn't seem to be part of CI so I'm not sure what's the state of it.
> chore: run cargo clippy --fix

- src/interpreter.rs
Unless I'm missing something or there's some planned feature, the `&Context` doesn't need to be `mut`
> feat(interpreter): use the immutable reference of `Context` in the `execute` method

- src/context.rs
- src/lib.rs
- src/router.rs
- src/schema.rs
According to [`std::fmt` docs](https://doc.rust-lang.org/stable/std/fmt/index.html#fmtdisplay-vs-fmtdebug) this should be implemented for all public types.
> feat: derive `Debug` for all public types

- src/cir.rs
[KAG-6094](https://konghq.atlassian.net/browse/KAG-6094)
[KAG-6094]: https://konghq.atlassian.net/browse/KAG-6094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> perf(cir): special treatment for single-predicate expression

- .github/workflows/tests.yml
update to ubuntu 22.04 and OpenResty 1.27.1.x
KAG-6866
> chore(ci): bump to ubuntu-22.04 and OpenResty matrix

- src/parser.rs
I've opened https://github.com/Kong/public-shared-actions/issues/268 for this but the action we're using uses the deprecated `actions-rs/toolchain` and also doesn't allow pinning the rust version so this started failing when 1.88 was released
> chore: fix clippy::uninlined_format_args error

- src/ast.rs
Should we also `impl`/`derive` `Eq`?
> feat: derive `PartialEq`, `Eq` for `ast::Expression`

- src/semantics.rs
[KAG-7221](https://konghq.atlassian.net/browse/KAG-7221) 
Code clean:
- const string for err message
- `raise_err()` to simplify error handling
- `use` in funtions
[KAG-7221]: https://konghq.atlassian.net/browse/KAG-7221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(src): code clean for semantics

- src/ffi/context.rs
- src/ffi/expression.rs
- src/ffi/router.rs
- src/router.rs
This PR introduces a new way of initializing ATC so that it *owns* the schema that it depends on, instead of relying on a shared reference.
This facilitates the workflow especially when ATC is instantiated and used in Rust libraries, particularly in use cases where it needs to be cached for reuse - so that it is not necessary to maintain a reference to an external Schema object.
This is based on @lucab 's [work](https://github.com/lucab/atc-router/pull/1/files) and includes some small changes that are a follow up to his observations (same PR).
HOUD-98
> feat(*): schema owned or referenced

- src/context.rs
- src/router.rs
https://konghq.atlassian.net/browse/KAG-7221
It may improve the performance of `try_match()` a little.
In `m.execute()`, `mat` may allocate memory in hashmap, the PR could reuse these memory to avoid re-allocating.
> refactor(src): add `reset()` for Match

- src/ffi/router.rs
- src/router.rs
update the router to accept types that implement `Borrow<Schema>` instead of using the `SchemaOwnedOrRef` type and multiple constructors.
This allows for more flexibility in how schemas are passed to the router while keeping the size of the router unchanged for FFI instantiations.
[HOUD-98]
[HOUD-98]: https://konghq.atlassian.net/browse/HOUD-98?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(*): Router takes Borrow<Schema> parameter
